// Облегчение жизни :)

export const CREATE_POST = "POST/CREATE_POST"
export const FETCH_POSTS = "POST/FETCH_POST"
export const REQUEST_POSTS = "POST/REQUEST_POSTS"
export const SHOW_LOADER = "APP/SHOW_LOADER"
export const HIDE_LOADER = "APP/HIDE_LOADER"
export const SHOW_EMPTY_INPUT_ALERT = "APP/SHOW_EMPTY_INPUT_ALERT"
export const HIDE_EMPTY_INPUT_ALERT = "APP/HIDE_EMPTY_INPUT_ALERT"